filebeat.inputs:
- type: log
  # Change to true to enable this input configuration.
  enabled: true
  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /cowrie_data/log/cowrie/cowrie.json

  json.keys_under_root: true
  json.add_error_key: true  
  tags: ["cowrie"]
  fields:
    honeypot_id: IME_HONEYPOTA


#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["XXX.XXX.XXX.XXX:5044"]
