apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cowrie-honeypots
spec:
  selector:
    matchLabels:
      name: cowrie-honeypots
    template:
      metadata:
        labels:
          name: cowrie-honeypots
      spec:
        containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.6.0
          resources:
            limits:
              memory: "300Mi"
              cpu: "0.3"
            requests:
              memory: "300Mi"
              cpu: "0.3"
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          volumeMounts:
          - name: cowrie-log-volume
            mountPath: /cowrie-data
          - name: cowrie-filebeat-config
            mountPath: /usr/share/filebeat/filebeat.yml
            subPath: filebeat.yml
        volumes:
        - name: cowrie-log-volume
          emptydir:
            sizeLimit: 100Mi
        

    