version: '2.4'

services:
  ubuntu-ssh:
    container_name: backend-pool-ssh-test
 #   user: admin
    restart: always
    cap_drop:
    - SETPCAP
    - MKNOD
    - NET_RAW
    - DAC_OVERRIDE
    - NET_BIND_SERVICE
    hostname: compute-node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "51006:22222"
    mem_limit: 500M  # limit the usage of memory to 500MB
    mem_reservation: 50m  # limit the usage of CPU to 25% of 400%
    cpus: 0.5