apiVersion: v1
kind: ConfigMap
metadata:
  name: cowrie-filebeat1-config-vXX-XX
  labels:
    name: cowrie-filebeat1-config-vXX-XX
data:
  config: |-
    #----------------------------- Logstash input --------------------------------
    filebeat.inputs:
    - type: log
      # Change to true to enable this input configuration.
      enabled: true
      # Paths that should be crawled and fetched. Glob based paths.
      paths:
        - /cowrie-data/log/cowrie/cowrie.json

      json.keys_under_root: true
      json.add_error_key: true  



    # Optional fields that you can specify to add additional information to the
    # output.
    fields:
      type: ${MY_NODE_NAME}


    #----------------------------- Logstash output --------------------------------
    #The Console output writes events in JSON format to stdout.
    #output.console:
      #If pretty is set to true, events written to stdout will be nicely formatted. The default is false.
      #pretty: true
    output.logstash:
      # The Logstash hosts
      hosts: ["XXX"]
